/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ImportRouteImport } from './routes/import'
import { Route as OptionsRouteImport } from './routes/options'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RiskRouteImport } from './routes/risk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsRoute = OptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backtest': typeof BacktestRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/help': typeof HelpRoute
  '/import': typeof ImportRoute
  '/options': typeof OptionsRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backtest': typeof BacktestRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/help': typeof HelpRoute
  '/import': typeof ImportRoute
  '/options': typeof OptionsRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backtest': typeof BacktestRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/help': typeof HelpRoute
  '/import': typeof ImportRoute
  '/options': typeof OptionsRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backtest'
    | '/diagnostics'
    | '/help'
    | '/import'
    | '/options'
    | '/portfolio'
    | '/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/backtest'
    | '/diagnostics'
    | '/help'
    | '/import'
    | '/options'
    | '/portfolio'
    | '/risk'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backtest'
    | '/diagnostics'
    | '/help'
    | '/import'
    | '/options'
    | '/portfolio'
    | '/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacktestRoute: typeof BacktestRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  HelpRoute: typeof HelpRoute
  ImportRoute: typeof ImportRoute
  OptionsRoute: typeof OptionsRoute
  PortfolioRoute: typeof PortfolioRoute
  RiskRoute: typeof RiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacktestRoute: BacktestRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  HelpRoute: HelpRoute,
  ImportRoute: ImportRoute,
  OptionsRoute: OptionsRoute,
  PortfolioRoute: PortfolioRoute,
  RiskRoute: RiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
